### ISSUE TITLE
Create html page with form and output area

### ISSUE THREAD

**Issue by StrangrDangr** [StrangrDangr/pokemon-move-converter-for-astral#1]
This just needs to be a standard html doc with a form and output area. It'll need to link to jquery and the unmade js and css.
For the form, we'll need :
-mid-long text fields for move name, description, and miscellaneous effects
-short text fields? for power, accuracy, and pp
-dropdowns for type, move type,
-two sections for random additional effects
-check box for Same Type Advantage

the output area should have a unique IDs for title, sheet display, and message section

**Comment by nutmegprince** [comment]
I can do it

**Comment by StrangrDangr** [comment]
I forgot a few things when I wrote this issue. We need some extra radio buttons and/or checkboxes.
-target radio buttons. the default can just be default, but the other options should be Adjacent Enemies, All Enemies, All Adjacent, All Allies, All
-Priority radio buttons should have default, priority, priority 2, and goes last
-Increased Crit Rate check box
